name: e_library
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  adaptive_theme: ^3.7.0
  dio: ^5.7.0
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  infinite_scroll_pagination: ^4.1.0
  logger: ^2.5.0
  shimmer_animation: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
